### ISSUE TITLE
Divergent color scales

### ISSUE THREAD

**Issue by bagordon** [ggseg/ggseg#61] opened 2021-06-11 19:26 UTC
I'm using the geom_brain options and I want to use a divergent color scale. It works okay if I use something like scale_fill_continuous_diverging(palette = "Blue-Red 3", l1 = 10, l2 = 100, p1 = 1, p2 = 1.5 it works okay as does using scale_fill_distiller with a command like this (scale_fill_distiller(palette = "RdBu", limits = c(-1,1)*max(abs(VARIABLE)))

In other options it doesn't recognize the bidirectional nature of the scale. For example scale_color_gradient(low="blue", high="red") only uses blue, no reds. The same thing happens if I use scale_fill_continuous_divergingx.

**Comment by Athanasiamo** [comment] 2021-08-09 11:13
Thanks for the issue. I have found the culprit in the code, and it should be fixed in the next release. Its related to underlying ggplot2 code that has changed, which also is reported in #63 and #60

**Comment by Athanasiamo** [comment] 2021-08-10 08:38
Please try downloading the new version on github. It should fix the issues caused by underlying changes to ggplot2. Let me know how it work for you!

**Closed** 2021-11-01 07:18 UTC
